### ISSUE TITLE
Why exec instead of available module?

### ISSUE THREAD

**Issue by jason-dour-e** [bep/gitmap#16]
Hello.  :)

Arrived here while investigating Hugo Issue 5533, which lead me to digging into branches, Hugo code, et cetera.  Which lead me to here.

I've long needed this sort of sub-module or Hugo-module capability; for years I've been employing work-arounds.

I did not realize Hugo relies on this module for its git information. Just stumbled across this today.

I'm curious why this route of executing `git` was chosen, versus using a Go module such as https://github.com/go-git/go-git?  Perhaps Hugo predates this or other Go git modules?

I have used `go-git` for several years.  Have found it incredibly efficient at parsing repositories so I can leverage them in my Go projects.  Notably, in my project https://github.com/jason-dour/hugo-preproc, so I could dynamically generate Hugo .md files for git commit histories as part of website projects.

If you think such a switch to a go library could be of use (i.e. native data structures with which complex filtering or other operations would be Go native), I'd be happy to look into submitting a PR that might help move to it, which might help make ideas like sub-module repos or Hugo-modules availability of GitInfo less of a time sink.

Thanks for Hugo! :)
Jason

**Comment by bep** [comment]
>I'm curious why this route of executing git was chosen, versus using a Go module such as https://github.com/go-git/go-git? Perhaps Hugo predates this or other Go git modules?

Well...

1. This is plenty fast enough for the 1 git command we need.
2. This has 0 dependendices.
3. [go-git](https://github.com/go-git/go-git) has hundreds of dependencies and a million codelines we don't use

We just want to do a ... `git log`.
